# Generated by Django 3.2.3 on 2024-02-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Полное название'),
        ),
    ]
