# Generated by Django 3.2.3 on 2024-02-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_ingredient_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='measurement_unit',
        ),
    ]
