# Generated by Django 3.2.3 on 2024-03-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('user__last_name', 'author__last_name'), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
