# Generated by Django 3.2.3 on 2024-03-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Таг', 'verbose_name_plural': 'Таги'},
        ),
    ]
