# Generated by Django 3.2.3 on 2024-02-19 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ингридиента рецепта', 'verbose_name_plural': 'Ингридиенты рецепта'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Таг рецепта', 'verbose_name_plural': 'Таги рецепта'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_in_recipe', to='recipes.recipe'),
        ),
    ]
