# Generated by Django 3.2.3 on 2024-02-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_userfavorite_usershoppingcart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usershoppingcart',
            options={'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipes/', verbose_name='Картинка'),
        ),
    ]
