# Generated by Django 3.2.3 on 2024-02-28 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_alter_ingredient_measurement_unit'),
        ('recipes', '0010_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_have_ingredient', to='ingredients.ingredient'),
        ),
    ]
